# Generated by Django 2.1.1 on 2021-03-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Minimum', models.IntegerField()),
                ('Maximum', models.IntegerField()),
            ],
        ),
    ]
