# Generated by Django 2.1.1 on 2021-03-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Description', models.CharField(max_length=30)),
                ('Image_path', models.CharField(max_length=30)),
                ('Quanity', models.IntegerField()),
            ],
        ),
    ]
