# Generated by Django 2.1.1 on 2021-03-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board_App', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Addr', models.IntegerField()),
                ('Unit', models.IntegerField()),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.IntegerField()),
                ('PO_Box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('created', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
